server:
  port: 8080
  session-timeout: 1800
  servlet:
    context-path: /SmartControl
  defaultCharset: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  ## 环境 dev|test|prod
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    encoding: utf-8
    cache: false
    suffix: .html
    mode: HTML
    enabled: true
    servlet:
      content-type: text/html
    check-template-location: true
  redis:
  # Redis数据库索引（默认为0）
    database: 1
  # Redis服务器地址
    host: 192.168.17.18
  # Redis服务器连接端口
    port: 6379
  # Redis服务器连接密码（默认为空）
    password: cathome
    timeout: 1800
  jedis:
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
       # 连接池中的最大空闲连接
      max-idle: 50
      # 连接池中的最小空闲连接
      min-idle: 8
  #mongodo配置
  data:
    mongodb:
      host: 192.168.17.18
      port: 27017
      uri: mongodb://192.168.17.18/mongo

logging:
  config: classpath:log4j2.yml
shiro:
  redis:
    expire: 1800

mybatis-plus:
  typeAliasesPackage: com.ciwr.modle.*
  config-location: classpath:/mybatis/mybatis-config.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#文件上传路径
upload:
  path: /opt/upload
  delimiter: '-'

# 项目根目录
baseUrl: http://localhost:8080/SmartControl/
#debug: true

