CREATE TABLE `sys_role` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权限ID',
  `role_name` VARCHAR(255) DEFAULT NULL COMMENT '权限名称',
  `role_module` VARCHAR(255) DEFAULT NULL COMMENT '权限对应的模块',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `create_user` BIGINT(20) DEFAULT NULL COMMENT '创建人',
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间(默认当前时间)',
  `is_del` TINYINT(1) DEFAULT '0' COMMENT '删除状态(0,未删除1,已删除)',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='权限表';
