CREATE TABLE `sys_role_menu` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT  '权限对应模块ID',
  `role_id` BIGINT(20) DEFAULT NULL COMMENT '权限ID',
  `menu_id` BIGINT(20) DEFAULT NULL COMMENT '菜单ID',
   PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='权限对应模块表';

