CREATE TABLE `sys_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '操作员id',
  `user_name` VARCHAR(32) DEFAULT NULL COMMENT '操作员登陆账户',
  `password` VARCHAR(100) DEFAULT NULL COMMENT '操作员登陆密码',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT '操作员电话',
  `email` VARCHAR(32) DEFAULT NULL COMMENT '操作员邮箱',
  `status` TINYINT(1) DEFAULT '1' COMMENT '是否启用(1:启用,0:不启用)',
  `create_user` BIGINT(20) DEFAULT NULL COMMENT '创建人',
  `create_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间(默认当前时间)',
  `is_del` TINYINT(1) DEFAULT '0' COMMENT '删除状态(0,未删除1,已删除)',
  `location` VARCHAR(64) DEFAULT NULL COMMENT '操作员最后一次登陆的IP地址',
  `last_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '操作员最后一次登陆的时间',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COMMENT='用户表';
