CREATE TABLE `sys_user_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '权限用户表ID',
  `role_id` BIGINT(20) DEFAULT NULL COMMENT '权限ID',
  `user_id` BIGINT(20) DEFAULT NULL COMMENT '用户ID',
 PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='用户对应权限表';
